frontend:
  image: ctfd/ctfd:latest
  db_user: root
  db_pass: pass
  db_host: host
  db_name: db
  db_port: 25060
  redis_user: default
  redis_pass: pass
  redis_host: host
  redis_port: 25061
  domain: myctf.ca
  tls:
    cert: 
    key: 
provider: DO