{{ if eq .Values.provider "local" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: upload-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/eric/k8"
{{ end }}