apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfd-frontend-deployment
  labels:
    app: ctfd-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctfd-frontend
  template:
    metadata:
      labels:
        app: ctfd-frontend
    spec:
      volumes:
        - name: ctfd-frontend-deployment-uploads-volume
          persistentVolumeClaim:
            claimName: upload-pvc
      containers:
      - name: ctfd
        image: {{ .Values.frontend.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: "/var/uploads"
          name: ctfd-frontend-deployment-uploads-volume
        env:
          - name: UPLOAD_FOLDER
            value: "/var/uploads"
          - name: DATABASE_URL
            value: mysql+pymysql://{{ .Values.frontend.db_user }}:{{ .Values.frontend.db_pass }}@{{ .Values.frontend.db_host }}:{{ .Values.frontend.db_port }}/{{ .Values.frontend.db_name }}
          - name: REDIS_URL
            value: rediss://{{ .Values.frontend.redis_user }}:{{ .Values.frontend.redis_pass }}@{{ .Values.frontend.redis_host }}:{{ .Values.frontend.redis_port }}
          - name: WORKERS
            value: "1"
          - name: LOG_FOLDER
            value: "/var/log/CTFd"
          - name: ACCESS_LOG
            value: "-"
          - name: ERROR_LOG
            value: "-"
---
apiVersion: v1
kind: Service
metadata:
  name: ctfd-frontend-service
spec:
  selector:
    app: ctfd-frontend
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: v1
data:
  tls.crt: {{ .Values.frontend.tls.cert }}
  tls.key: {{ .Values.frontend.tls.key }}
kind: Secret
metadata:
  name: ctfd-frontend-tls
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ctfd-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: cookie
spec:
  tls:
  - hosts:
    - {{ .Values.frontend.domain }}
    secretName: ctfd-frontend-tls
  rules:
  - host: {{ .Values.frontend.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ctfd-frontend-service
            port: 
              number: 80
